GRAD_STASI_CHECKTRACKER_FAST = 0.5; // with welding trolley
GRAD_STASI_CHECKTRACKER_SLOW = 5; // without welding trolley

GRAD_STASI_MIC_MAX_DISTANCE = 150;
GRAD_STASI_MIC_MIN_DISTANCE = 1;
GRAD_STASI_MIC_CURRENT_DISTANCE = 1;