name = "GRAD Stasi"
prefix = "grad_stasi"
author = "nomisum, Salbei"
files = [
    "mod.cpp",
    "logo_grad_ca.paa",
    "LICENSE",
    "README.md"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip grad_stasi_{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
]

[header_exts]
version= "{{git \"id 8\"}}"